# Numeric / currencies
MON_DECIMAL_POINT = ','
MON_THOUSANDS_SEP = ' '
N_CS_PRECEDES = 0
P_CS_PRECEDES = 0
N_SEP_BY_SPACE = 1
P_SEP_BY_SPACE = 1
N_SIGN_POSN = 1
P_SIGN_POSN = 1
NEGATIVE_SIGN = '-'
POSITIVE_SIGN = ''

# Dates
DATEPICKER_FORMAT = 'd/m/Y'
EVENT_DATE_FORMAT = 'l j F Y'               # Lundi 25 octobre 2006
EVENT_DATETIME_FORMAT = 'l j F Y H:i'       # Lundi 25 octobre 2006 14:30
EVENT_SHORT_DATE_FORMAT = 'j N Y'           # 25 oct. 2006
EVENT_SHORT_DATETIME_FORMAT = 'j N Y H:i'   # 25 oct. 2006 14:30
EVENT_HOUR_DATETIME_FORMAT = 'H:i'          # 14:30