# -*- coding:Utf-8 -*-

HELP_TEXT = {
    'timeline_entry': {
        'module': 'Module related to the timeline',
        'datetime': 'Datetime of the timeline entry',
        'issuer': 'User which have done an action resulting in the timeline entry creation',
    },
    'entity_saved': {
        'created': 'Indicates if the contact/organization has been created or updated',
        'contact': 'The contact saved',
        'organization': 'The organization saved',
    },
    'invoicebase_saved': {
        'created': 'Indicates if the quotation/invoice/credit note has been created or updated',
        'quotation_reference': 'The reference of the quotation',
        'purchase_order_reference': 'The reference of the purchase order',
        'invoice_reference': 'The reference of the invoice',
        'down_payment_invoice_reference': 'The reference of the down-payment invoice',
        'credit_note_reference': 'The reference of the credit note',
        'quotation': 'The quotation saved',
        'purchase_order': 'The purchase order saved',
        'invoice': 'The invoice saved',
        'down_payment_invoice': 'The down-payment invoice saved',
        'credit_note': 'The credit note saved',
        'customer_display': 'Customer\'s representation',
        'contact': 'The related contact',
        'organization': 'The related organization',
        'has_temporary_reference': 'Invoice/Down-payment invoice temporary reference status',
    },
    'invoicebase_changed_state': {
        'quotation': 'Quotation whose state has changed',
        'purchase_order': 'Purchase order whose state has changed',
        'invoice': 'Invoice whose state has changed',
        'down_payment_invoice': 'Down-payment invoice whose state has changed',
        'credit_note': 'Credit note whose state has changed',
        'previous_state': 'Previous state of the quotation/invoice/credit note',
        'new_state': 'New state applied to the quotation/invoice/credit note',
    },
    'quotation_make_purchase_order': {
        'quotation_reference': 'The reference of the quotation',
        'purchase_order_reference': 'The reference of the purchase order',
        'customer_display': 'Customer\'s representation',
        'quotation': 'The quotation from which the purchase order has been made',
        'purchase_order': 'The generated purchase order',
    },
    'quotation_make_invoice': {
        'quotation_reference': 'The reference of the quotation',
        'invoice_reference': 'The reference of the invoice',
        'customer_display': 'Customer\'s representation',
        'has_temporary_reference': 'Invoice/Down-payment invoice temporary reference status',
        'quotation': 'The quotation from which the invoice has been made',
        'invoice': 'The generated invoice',
    },
    'quotation_make_down_payment_invoice': {
        'down_payment_invoice_reference': 'The reference of the down_payment_invoice',
        'down_payment_invoice': 'The generated down-payment invoice',
    },
    'purchase_order_make_invoice': {
        'purchase_order_reference': 'The reference of the purchase_order',
        'invoice_reference': 'The reference of the invoice',
        'customer_display': 'Customer\'s representation',
        'has_temporary_reference': 'Invoice/Down-payment invoice temporary reference status',
        'purchase_order': 'The purchase_order from which the invoice has been made',
        'invoice': 'The generated invoice',
    },
    'purchase_order_make_down_payment_invoice': {
        'down_payment_invoice_reference': 'The reference of the down_payment_invoice',
        'down_payment_invoice': 'The generated down-payment invoice',
    },
    'invoice_cancelled': {
        'invoice': 'The cancelled invoice',
        'down_payment_invoice': 'The cancelled down-payment invoice',
        'credit_note': 'The generated credit note',
    },
}
